import { TodoType } from '@/entities/todo'

export const DEFAULT_TODOS: TodoType[] = [
  { id: 1, title: 'Купить хлеб', isCompleted: false },
  {
    id: 2,
    title: 'Купить протеин',
    description:
      'Биохимический элемент в форме органического соединения, состоящий из набора аминокислот.',
    isCompleted: true,
  },
  { id: 3, title: 'Сходить в спортзал', isCompleted: false },
  {
    id: 4,
    title: 'Прочитать статью про React',
    description: 'Фреймворк для создания пользовательских интерфейсов.',
    isCompleted: true,
  },
  { id: 5, title: 'Убрать в комнате', isCompleted: false },
  { id: 6, title: 'Позвонить родителям', isCompleted: false },
  {
    id: 7,
    title: 'Выучить 10 английских слов',
    description: 'Повышение словарного запаса для повседневного общения.',
    isCompleted: true,
  },
  { id: 8, title: 'Сделать зарядку', isCompleted: true },
  {
    id: 9,
    title: 'Посмотреть вебинар по TypeScript',
    description: 'Типизированное расширение JavaScript.',
    isCompleted: false,
  },
  { id: 10, title: 'Протестировать новый компонент UI', isCompleted: false },
  {
    id: 11,
    title: 'Обновить резюме',
    description: 'Добавить последние проекты и навыки.',
    isCompleted: false,
  },
  { id: 12, title: 'Купить подарки на день рождения', isCompleted: true },
  {
    id: 13,
    title: 'Разобраться с git rebase',
    description: 'Полезно для чистой истории коммитов.',
    isCompleted: false,
  },
  { id: 14, title: 'Написать статью в блог', isCompleted: false },
  { id: 15, title: 'Посадить цветы', isCompleted: false },
  {
    id: 16,
    title: 'Сделать бэкап данных',
    description: 'Сохранение копий важных файлов.',
    isCompleted: true,
  },
  { id: 17, title: 'Погулять на свежем воздухе', isCompleted: false },
  {
    id: 18,
    title: 'Сварить борщ',
    description: 'Классическое украинское блюдо на обед.',
    isCompleted: true,
  },
  { id: 19, title: 'Пройти курс по тестированию', isCompleted: false },
  { id: 20, title: 'Заказать воду', isCompleted: true },
  {
    id: 21,
    title: 'Посмотреть видео про useEffect',
    description: 'Хук для побочных эффектов в React.',
    isCompleted: false,
  },
  { id: 22, title: 'Написать тесты для API', isCompleted: false },
  { id: 23, title: 'Провести ревизию расходов', isCompleted: true },
  {
    id: 24,
    title: 'Настроить ESLint',
    description: 'Инструмент для обеспечения качества кода.',
    isCompleted: false,
  },
  { id: 25, title: 'Подготовить доклад', isCompleted: true },
  { id: 26, title: 'Разобрать папку “Загрузки”', isCompleted: false },
  {
    id: 27,
    title: 'Написать отзыв о курсе',
    description: 'Поможет другим принять решение о прохождении.',
    isCompleted: true,
  },
  { id: 28, title: 'Настроить фильтры в приложении', isCompleted: false },
  { id: 29, title: 'Выбросить мусор', isCompleted: true },
  {
    id: 30,
    title: 'Сделать паузу и отдохнуть',
    description: 'Восстановление энергии и фокуса.',
    isCompleted: false,
  },
]
